name: "📱 Add Client"
description: >
  Do you have a client that is not yet listed and want it to be listed in the repo?

title: "Add Client <client>"
labels:
  - request
  - client

body:      
  - type: input
    id: project-website
    attributes:
      label: Project Website
      description: Link to the project (e.g. GitHub)
      placeholder: ex. https://github.com/awesome-jellyfin/awesome-jellyfin
    validations:
      required: true
      
  - type: checkboxes
    id: targets
    attributes:
      label: Targets
      description: Which platforms does the client target?
      options:
        - label: Browser
        - label: Windows
        - label: macOS
        - label: Linux
        - label: iOS
        - label: Android
        - label: Sailfish OS
        - label: HarmonyOS
        - label: Nintendo Switch
        - label: Apple TV
        - label: Android TV
        - label: Kodi
        - label: Roku
        - label: WebOS
      
  - type: checkboxes
    id: price
    attributes:
      label: Price
      description: In-App Purchases should be marked as Paid
      options:
        - label: Free
        - label: Paid
